### ISSUE TITLE
Cursor movement using up and down arrow keys

### ISSUE THREAD

**Issue by burntcarrot** [burntcarrot/pairpad#20]
Right now, the cursor movement happens using the left and right arrow keys.

For a better user experience, navigation using the up and down arrow keys would be nice to have.

I have a basic idea on how it would work:
- compute the length of each "block"/segment inside the editor
- get the largest block, and set the max length to the block's length
- use the max length to "pad" other blocks virtually
- now, safely compute cursor positions
- incase the cursor position "overflows", set the cursor to the block's `end_pos + 1`

**Comment by benmuth** [comment]
#24 is a possible solution. The cursor behavior works as intended and should be pretty fast in all cases, but is definitely not the cleanest implementation.
